sudo: required

language: node_js

node_js:
  - "node"
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ];
    then
      yarn deploy;
    fi