// flow-typed signature: 939ff55350a00e34c0c3ab3e89c01d49
// flow-typed version: <<STUB>>/draft-js-inline-toolbar-plugin_v^2.0.0-rc2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-inline-toolbar-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-inline-toolbar-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-inline-toolbar-plugin/lib/components/Separator/index' {
  declare module.exports: any;
}

declare module 'draft-js-inline-toolbar-plugin/lib/components/Toolbar/index' {
  declare module.exports: any;
}

declare module 'draft-js-inline-toolbar-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-inline-toolbar-plugin/lib/utils/createStore' {
  declare module.exports: any;
}

declare module 'draft-js-inline-toolbar-plugin/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-inline-toolbar-plugin/lib/components/Separator/index.js' {
  declare module.exports: $Exports<'draft-js-inline-toolbar-plugin/lib/components/Separator/index'>;
}
declare module 'draft-js-inline-toolbar-plugin/lib/components/Toolbar/index.js' {
  declare module.exports: $Exports<'draft-js-inline-toolbar-plugin/lib/components/Toolbar/index'>;
}
declare module 'draft-js-inline-toolbar-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-inline-toolbar-plugin/lib/index'>;
}
declare module 'draft-js-inline-toolbar-plugin/lib/utils/createStore.js' {
  declare module.exports: $Exports<'draft-js-inline-toolbar-plugin/lib/utils/createStore'>;
}
declare module 'draft-js-inline-toolbar-plugin/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-inline-toolbar-plugin/postcss.config'>;
}
