// flow-typed signature: b3e5d36cddd93d24d81000a7e4b719b4
// flow-typed version: <<STUB>>/reapop-theme-wybo_v^0.4.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reapop-theme-wybo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reapop-theme-wybo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'reapop-theme-wybo/index' {
  declare module.exports: $Exports<'reapop-theme-wybo'>;
}
declare module 'reapop-theme-wybo/index.js' {
  declare module.exports: $Exports<'reapop-theme-wybo'>;
}
