// flow-typed signature: 299caa6dd594940bc4084a92f7b19166
// flow-typed version: <<STUB>>/reapop-theme-bootstrap_v^0.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reapop-theme-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reapop-theme-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'reapop-theme-bootstrap/index' {
  declare module.exports: $Exports<'reapop-theme-bootstrap'>;
}
declare module 'reapop-theme-bootstrap/index.js' {
  declare module.exports: $Exports<'reapop-theme-bootstrap'>;
}
