// flow-typed signature: 5a13687e505ab3499d47cfc3f1b99bf6
// flow-typed version: <<STUB>>/reapop_v^1.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reapop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reapop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reapop/lib/components/Notification' {
  declare module.exports: any;
}

declare module 'reapop/lib/components/NotificationsContainer' {
  declare module.exports: any;
}

declare module 'reapop/lib/components/NotificationsSystem' {
  declare module.exports: any;
}

declare module 'reapop/lib/constants/index' {
  declare module.exports: any;
}

declare module 'reapop/lib/helpers/index' {
  declare module.exports: any;
}

declare module 'reapop/lib/index' {
  declare module.exports: any;
}

declare module 'reapop/lib/store/notifications' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reapop/lib/components/Notification.js' {
  declare module.exports: $Exports<'reapop/lib/components/Notification'>;
}
declare module 'reapop/lib/components/NotificationsContainer.js' {
  declare module.exports: $Exports<'reapop/lib/components/NotificationsContainer'>;
}
declare module 'reapop/lib/components/NotificationsSystem.js' {
  declare module.exports: $Exports<'reapop/lib/components/NotificationsSystem'>;
}
declare module 'reapop/lib/constants/index.js' {
  declare module.exports: $Exports<'reapop/lib/constants/index'>;
}
declare module 'reapop/lib/helpers/index.js' {
  declare module.exports: $Exports<'reapop/lib/helpers/index'>;
}
declare module 'reapop/lib/index.js' {
  declare module.exports: $Exports<'reapop/lib/index'>;
}
declare module 'reapop/lib/store/notifications.js' {
  declare module.exports: $Exports<'reapop/lib/store/notifications'>;
}
